template = "https://github.com/giellalt/template-lang-und"
rev_id = 337
template_sha = "1c2fffaa917a9c6f340d9887d554609eb561ade6"

[replacements]
__GLOTTOLOG_ID__ = "lule1254"
__REPO__ = "lang-smj"
__UND2C__ = "smj"
__UNDEFINED__ = "Lule Sami"
__UND__ = "smj"
