template = "https://github.com/giellalt/template-lang-und"
rev_id = 290
template_sha = "8bd07bd7ffd9976018537ac052a0fed5be7be8a3"

[replacements]
__GLOTTOLOG_ID__ = "lule1254"
__REPO__ = "lang-smj"
__UND2C__ = "smj"
__UNDEFINED__ = "Lule Sami"
__UND__ = "smj"
