template = "https://github.com/giellalt/template-lang-und"
rev_id = 310
template_sha = "2b86b7b0f15ed9573072d140b76c5cc65c03503c"

[replacements]
__GLOTTOLOG_ID__ = "lule1254"
__REPO__ = "lang-smj"
__UND2C__ = "smj"
__UNDEFINED__ = "Lule Sami"
__UND__ = "smj"
