[package]
name = "smj"
human_name = "Lule Sami"
version = "4.2.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.smj]
filename = "smj-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-smj"
platform = "windows"
uuid = "9C8132E7-8FF9-4707-8FEA-0CA2C8959AD0"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.smj"
package = "speller-smj"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-smj-mso"
platform = "windows"
uuid = "E2FE02AD-0B19-4F6B-B91B-08408165C520"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-smj"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
